version: "3.9"
services:
  # Postgres DB
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./back-end/postgres_db:/var/lib/postgresql/data/

  # React
  react:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    command: yarn run dev
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules

  # Django back-end
  web:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: sh /back-end/start.sh
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - PYTHONUNBUFFERED=1
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./back-end:/back-end
    depends_on:
      - database