# Generated by Django 3.1.7 on 2023-09-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
